"""initial schema

Revision ID: 51f8858f3a3a
Revises: 
Create Date: 2026-07-14 23:11:23.593427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51f8858f3a3a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materials',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('min_stock', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipes',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('produces', sa.String(length=255), nullable=False),
    sa.Column('batch_yield', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('technology', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('fio', sa.String(length=255), nullable=False),
    sa.Column('login', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('messenger', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('document', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=True)
    op.create_table('feedback',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('author_id', sa.String(length=8), nullable=False),
    sa.Column('author_role', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_log',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('worker_id', sa.String(length=8), nullable=False),
    sa.Column('recipe_id', sa.String(length=8), nullable=False),
    sa.Column('batches', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=False),
    sa.Column('defects', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('gtin', sa.String(length=50), nullable=False),
    sa.Column('composition', sa.Text(), nullable=True),
    sa.Column('recipe_id', sa.String(length=8), nullable=True),
    sa.Column('tn_ved', sa.String(length=50), nullable=True),
    sa.Column('declaration', sa.String(length=255), nullable=True),
    sa.Column('declaration_expires', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipe_id', sa.String(length=8), nullable=False),
    sa.Column('material_id', sa.String(length=8), nullable=False),
    sa.Column('qty_per_batch', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipe_id', 'material_id', name='uq_recipe_item')
    )
    op.create_table('transactions',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('material_id', sa.String(length=8), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('recipe_id', sa.String(length=8), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('product_id', sa.String(length=8), nullable=False),
    sa.Column('qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales')
    op.drop_table('transactions')
    op.drop_table('recipe_items')
    op.drop_table('products')
    op.drop_table('production_log')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.drop_table('users')
    op.drop_table('recipes')
    op.drop_table('materials')
    # ### end Alembic commands ###
